# Midterm - Environmental & Health Impacts of Warehouses in Ontario, CA
Alejandra, Georgie, Jennifer, Matthews

## Data exploration

Exploring basic information of all the data of EJI, warehouses, and related facilities of Ontario city.

In [1]:
#importing the neccesary libraries

import pandas as pd
import geopandas as gpd
import osmnx as ox
import fiona

### Environmental and Health Data Exploration
---
 Loading cleaned, filtered, and merged Environmental Justice Index and Census Tract data
 
 See ['EJIData.ipynb'](https://jupyter.idre.ucla.edu/user/alrg@ucla.edu/lab/tree/UP221-cargo/Project%20Materials/EJIData.ipynb) notebook for full process

In [2]:
# Importing EJI file
EJI =gpd.read_file('../../Data/EJIselectdata.geojson')
EJI.head()

,state code,county code,affgeoid,geoid,county,location,Total Population,Day Population,EJI Rank,Environmental Burden Rank,...,"% Households < $75,000",% Uninsured,% No Internet,% Age 65+,% Age 17 or Younger,% With Disability,% Limited English,% Mobile Home,% Group Quarters,geometry
0,06,071,1400000US06071001307,06071001307,San Bernardino,"Census Tract 13.07, San Bernardino County, Calif",4212,2345,0.6649,0.8834,...,39.6300,10.6,14.3,9.1,26.3,8.9,10.3,0.0,0.2,"POLYGON ((-117.62857 34.09215, -117.62856 34.0..."
1,06,071,1400000US06071001703,06071001703,San Bernardino,"Census Tract 17.03, San Bernardino County, Calif",5680,2388,0.4366,0.6255,...,26.3285,7.0,5.6,13.6,19.4,7.8,8.1,10.8,0.6,"POLYGON ((-117.66764 34.03029, -117.66760 34.0..."
2,06,071,1400000US06071001812,06071001812,San Bernardino,"Census Tract 18.12, San Bernardino County, Calif",3477,2913,0.9054,0.9883,...,53.0762,13.0,26.5,11.1,26.0,11.4,18.2,0.0,1.8,"POLYGON ((-117.65077 34.04925, -117.65074 34.0..."
3,06,071,1400000US06071001002,06071001002,San Bernardino,"Census Tract 10.02, San Bernardino County, Calif",5929,1960,0.6587,0.7748,...,49.3195,13.9,24.3,6.4,30.3,7.2,13.3,0.0,0.0,"POLYGON ((-117.68082 34.07406, -117.68082 34.0..."
4,06,071,1400000US06071001310,06071001310,San Bernardino,"Census Tract 13.10, San Bernardino County, Calif",6193,2689,0.7382,0.9542,...,34.8688,6.4,13.6,12.1,27.3,10.2,12.5,0.9,3.2,"POLYGON ((-117.64145 34.08708, -117.64144 34.0..."

In [3]:
# Setting the crs to epsg:4326
EJI.crs = 'epsg:4326'

### Ontario Land Use Data Exploration

In [4]:
#defining the area of interest with an address
address = 'Ontario International Airport, Vineyard Avenue, Racimo, Ontario, San Bernardino County, California, 91761, United States'

In [5]:
#obtaining building data from OSM for the entire city
osm = ox.geometries_from_address(address,tags={'building':True},dist=5000)

In [6]:
#getting more info on the dataset
#determining hoow many rows/columns
osm.shape
#this dataset has 8264 rows and 133 columns

(3119, 130)

In [7]:
#determining datatype
type(osm)
#this is a geodataframe

geopandas.geodataframe.GeoDataFrame

In [8]:
#displaying 10 random rows
osm.head()

                       addr:state building  ele gnis:county_name  \
element_type osmid
node         368173617         CA      yes  377   San Bernardino
             479791356         CA      yes  NaN              NaN
             479791359         CA      yes  NaN              NaN
             479791362         CA      yes  NaN              NaN
             518277168         CA      yes  NaN              NaN

                       gnis:feature_id gnis:reviewed  \
element_type osmid
node         368173617         1844432            no
             479791356             NaN           NaN
             479791359             NaN           NaN
             479791362             NaN           NaN
             518277168             NaN           NaN

                                             name  \
element_type osmid
node         368173617  F C Crowell Memorial Hall
             479791356                        NaN
             479791359                        NaN
             479791362                        NaN
             518277168                     Subway

                                                            source  \
element_type osmid
node         368173617                               USGS Geonames
             479791356  survey;image;yahoo_imagry;local_government
             479791359  survey;image;yahoo_imagry;local_government
             479791362  survey;image;yahoo_imagry;local_government
             518277168                   image;survey;usgs_imagery

                                           geometry         addr:city  ...  \
element_type osmid                                                     ...
node         368173617  POINT (-117.65043 34.09696)               NaN  ...
             479791356  POINT (-117.54560 34.08149)  Rancho Cucamonga  ...
             479791359  POINT (-117.54563 34.08115)  Rancho Cucamonga  ...
             479791362  POINT (-117.54570 34.08083)  Rancho Cucamonga  ...
             518277168  POINT (-117.57604 34.08489)  Rancho Cucamonga  ...

                       content generator:method generator:output:electricity  \
element_type osmid
node         368173617     NaN              NaN                          NaN
             479791356     NaN              NaN                          NaN
             479791359     NaN              NaN                          NaN
             479791362     NaN              NaN                          NaN
             518277168     NaN              NaN                          NaN

                       generator:source generator:type power ways type  \
element_type osmid
node         368173617              NaN            NaN   NaN  NaN  NaN
             479791356              NaN            NaN   NaN  NaN  NaN
             479791359              NaN            NaN   NaN  NaN  NaN
             479791362              NaN            NaN   NaN  NaN  NaN
             518277168              NaN            NaN   NaN  NaN  NaN

                       service:vehicle:smog_check service:vehicle:tune
element_type osmid
node         368173617                        NaN                  NaN
             479791356                        NaN                  NaN
             479791359                        NaN                  NaN
             479791362                        NaN                  NaN
             518277168                        NaN                  NaN

[5 rows x 130 columns]

In [9]:
#removing unspecified/unknown building types from the data

osm.drop(osm.loc[osm['building']=='unspecified'].index,inplace=True)
osm.drop(osm.loc[osm['building']=='yes'].index,inplace=True)

In [10]:
#subsetting the data and defining which columns to keep
ctk=['geometry','building']
osm=osm[ctk]
osm.head()

                                           geometry building
element_type osmid
node         521362425  POINT (-117.59008 34.02953)    house
             521362429  POINT (-117.59027 34.02946)    house
             521362433  POINT (-117.59026 34.02885)    house
             521362436  POINT (-117.59004 34.02874)    house
             521362440  POINT (-117.59010 34.02860)    house

Now that the data is cleaned, we save the dataframe as a geojson:

In [11]:
#Save geodataframe as as geojson file
osm.to_file('../../Data/ontariolanduse.geojson', driver='GeoJSON', mode='w')

### Warehouse Data Exploration (for charts)

In [12]:
#loading first data file on warehouse information
wh = pd.read_csv('../../weekly tasks/week 4/W4-Georgie/warehouse (1).csv')
wh.head()

,Assessor parcel number,Building classification,Year built,Acres,Building sq.ft.
0,051513138,storage building,2021,275,7778022
1,046323158,distribution warehouse,2003,225,6381893
2,049202124,storage warehouse,2016,151,4273702
3,668280017,warehouse/dry storage,1910,128,3633789
4,046323161,distribution warehouse,2018,106,3014158

In [13]:
#generating statistics for acreage
wh['Acres'].describe()

count    9467.000000
mean        5.871237
std         9.138117
min         1.000000
25%         2.000000
50%         3.000000
75%         6.000000
max       275.000000
Name: Acres, dtype: float64

In [14]:
#sorting warehouses by acreage size
wh.sort_values(by='Acres', ascending=False)
wh.head()

,Assessor parcel number,Building classification,Year built,Acres,Building sq.ft.
0,051513138,storage building,2021,275,7778022
1,046323158,distribution warehouse,2003,225,6381893
2,049202124,storage warehouse,2016,151,4273702
3,668280017,warehouse/dry storage,1910,128,3633789
4,046323161,distribution warehouse,2018,106,3014158

In [15]:
#sorting warehouses by year built
wh.sort_values(by='Year built', ascending=True)
wh.head()

,Assessor parcel number,Building classification,Year built,Acres,Building sq.ft.
0,051513138,storage building,2021,275,7778022
1,046323158,distribution warehouse,2003,225,6381893
2,049202124,storage warehouse,2016,151,4273702
3,668280017,warehouse/dry storage,1910,128,3633789
4,046323161,distribution warehouse,2018,106,3014158

In [16]:
#removing 1910 value 
# '1910' is the year given to warehouses with an unknown construction date)
wh.drop(wh.loc[wh['Year built']==1910].index, inplace=True)

In [17]:
#checking for empty values
wh.columns[wh.isna().all()].tolist()

[]

In [18]:
#filtering out unwanted columns
desired_columns=['Acres','Year built', 'Building sq.ft.']

In [19]:
#creating a copy so that the table doesn't revert to the original data
wh_new=wh[desired_columns].copy()
wh_new.head()

   Acres  Year built  Building sq.ft.
0    275        2021          7778022
1    225        2003          6381893
2    151        2016          4273702
4    106        2018          3014158
5    106        1941          2990190

The dataframe of warehouses have been cleaned up to only information of acres, year built, and building sq.ft.

Now, we'll convert the dataframe to a csv:

In [20]:
#input: using pandas to covert the merged and filtered dataframe to a csv
#output: csv created but still needs to be saved
convertcsv= pd.DataFrame(wh_new)
csv_wh_new = convertcsv.to_csv(index=False)

In [21]:
#input: saving the data from the data frame into a the csv file created 
#output: file should appear on the folder
with open('../../Data/warehousecharts.csv', 'w') as csv_file:
    convertcsv.to_csv(path_or_buf=csv_file)

### Warehouse data exploration (for maps)

In [22]:
# See all the columns and rows.
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Import warehouse data and convert the datatype of 'Assessor parcel number' and 'Building classification' from 'int' or 'float' to 'str'
             
Warehouses = pd.read_csv('../../weekly tasks/week 4/Warehouse Data Exploration - Matthews/Data/Warehouse_Data.csv',
        dtype=
        {
            'Assessor parcel number':str,
            'Building classification':str,
        }
)

San_Bern_Parcels = gpd.read_file('../../weekly tasks/week 4/Warehouse Data Exploration - Matthews/Data/Ontario Parcels/SBCo_Parcel_Polygons.shp')

San_Bern_Parcels.rename(columns = {'ParcelNumb':'Assessor parcel number'}, inplace = True)

#merge the warehouses and parcel shapefile on the San Bernandino County Tax Assessor parcel Number
Warehouse_Parcel=Warehouses.merge(San_Bern_Parcels,on="Assessor parcel number")
Warehouse_Parcel_Geo = gpd.GeoDataFrame(Warehouse_Parcel, geometry='geometry', crs="EPSG:4326")

Warehouse_Parcel_Geo.head()

,Assessor parcel number,Building classification,Year built,Acres,Building sq.ft.,OBJECTID,OwnerName,LandValue,Improvemen,PersonalPr,ExemptionV,HomeOwnerE,Acreage,TaxStatus,TaxRateAre,Zoning,ZoningDesc,Jurisdicti,Jurisdic_1,BaseYear,PageMap,AssessDesc,AssessClas,Shape__Are,Shape__Len,geometry
0,023812175,distribution warehouse,1996,93,2646053,157685,TOYOTA MOTOR SALES U S A INC,"51,510,534","30,864,960",0,0,None,93.45,ASSESSED BY COUNTY,0004030,CITY OF ONTARIO,City of Ontario,City of Ontario,http://www.ci.ontario.ca.us/,1993,023812,DISTRIBUTION WAREHOUSE,COMMERCIAL,552237.437500,3009.581112,"POLYGON ((-117.55796 34.04799, -117.55689 34.0..."
1,021126319,transit warehouse (truck terminal),1992,70,1986082,123022,UPS WORLDWIDE FORWARDING INC,"25,587,357","54,634,664",0,0,None,66.66,ASSESSED BY COUNTY,0004004,CITY OF ONTARIO,City of Ontario,City of Ontario,http://www.ci.ontario.ca.us/,1992,021126,TRANSIT WAREHOUSE (TRUCK TERMINAL),INDUSTRIAL,414508.363281,2895.298085,"POLYGON ((-117.57896 34.04811, -117.57893 34.0..."
2,107311124,distribution warehouse,2021,62,1748594,685625,OLV PHASE II LP,"65,790,000","75,500,000",0,0,None,61.76,ASSESSED BY COUNTY,0004089,CITY OF ONTARIO,City of Ontario,City of Ontario,http://www.ci.ontario.ca.us/,2021,107311,DISTRIBUTION WAREHOUSE,INDUSTRIAL,364429.617188,2738.202572,"POLYGON ((-117.60640 33.99035, -117.60638 33.9..."
3,021121315,storage warehouse,1992,61,1723857,121965,UPS WORLDWIDE FORWARDING INC,"24,185,220","24,451,343",0,0,None,58.99,ASSESSED BY COUNTY,0004004,CITY OF ONTARIO,City of Ontario,City of Ontario,http://www.ci.ontario.ca.us/,1992,021121,STORAGE WAREHOUSE,COMMERCIAL,359815.906250,2461.426213,"POLYGON ((-117.58314 34.05195, -117.58208 34.0..."
4,023808145,distribution warehouse,1980,59,1681858,157834,COSTCO WHOLESALE CORPORATION,"76,500,000","147,900,000",0,0,None,59.42,ASSESSED BY COUNTY,0004025,CITY OF ONTARIO,City of Ontario,City of Ontario,http://www.ci.ontario.ca.us/,2021,023808,DISTRIBUTION WAREHOUSE,INDUSTRIAL,351134.007812,2355.939087,"POLYGON ((-117.53289 34.06252, -117.52727 34.0..."

In [23]:
#Save dataframe (Warehouse_Parcel)as as csv file

#input: using pandas to covert the merged and filtered dataframe to a csv
#output: csv created but still needs to be saved
convertcsv= pd.DataFrame(Warehouse_Parcel)
Warehouse_Parcel = convertcsv.to_csv(index=False)

In [24]:
#input: saving the data from the data frame into a the csv file created 
#output: file should appear on the folder
with open('../../Data/warehouseparcelmaps.csv', 'w') as csv_file:
    convertcsv.to_csv(path_or_buf=csv_file)

Now we save the other dataframe as a geojson

In [25]:
#Save geodataframe (Warehouse_Parcel_Geo) as as geojson file
Warehouse_Parcel_Geo.to_file('../../Data/warehousemaps.geojson', driver='GeoJSON', mode='w')